---
- hosts: hostList
  tasks:
    - name: Services cinder
      shell: sudo service {{item}} {{ operation }}
      become: yes
      with_items: 
        - cinder-api
        - cinder-scheduler
        - cinder-backup
        - cinder-volume
