- hosts: hostList
  serial: 1
  vars_files:
    - vars/cinder_info.yml
    - vars/proxy_info.yml
  tasks:
    - name: apt update
      shell: sudo apt-get update
    - name: install all cinder packages
      shell: sudo apt-get install -y --force-yes cinder-common python-cinder cinder-api cinder-scheduler cinder-volume cinder-backup python-metrics
    - name: Stop Services cinder
      service: name={{item}} state=stopped
      become: yes
      with_items: 
        - cinder-api
        - cinder-scheduler
        - cinder-backup
        - cinder-volume
    - name: Start Services cinder volume
      service: name=cinder-volume state=started
      run_once: true
      become: yes
