---
- hosts: supervisor-hostlist

  vars_files:
    - vars/proxy_info.yml
    - vars/supervisord.yml

  vars:
    proxy_env:
      http_proxy: http://{proxy_ip}:{proxy_port}

  tasks:
    - name: Install Supervisor
      apt: pkg=supervisor state=installed update_cache=true
      environment: "{{proxy_env}}"
      become: yes
