---
- hosts: telegraf-hostlist

  vars_files:
    - vars/telegraf.yml

  tasks:
#    Uncommenting this as this does not work
#    - name: Copy telegraf
#      template: src=telegraf-src/telegraf_0.11.1-1_amd64.deb dest=/tmp/
#      become: yes

    - name: Dpkg telegraf
      shell: sudo dpkg -i /tmp/telegraf_0.11.1-1_amd64.deb
      become: yes
