---
- hosts: telegraf-hostlist

  vars_files:
    - vars/telegraf.yml

  tasks:
    - name: Copy telegraf
      template: src=telegraf-src/telegraf_0.11.1-1_amd64.deb dest=/tmp/telegraf_0.11.1-1_amd64.deb
      become: yes

    - name: Dpkg telegraf
      shell: sudo dpkg -i telegraf_0.11.1-1_amd64.deb
      become: yes